apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: giropops-pass
  namespace: dk8s
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /giropops-senhas
        pathType: Prefix
        backend: 
          service: 
            name: giropops-pass
            port:
              number: 5000
